package cn.game.rjserver.uc.entity;

// Generated 2014-3-7 13:54:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TgsmServers generated by hbm2java
 */
public class TgsmServers implements java.io.Serializable {

	private Long serverid;
	private String servername;
	private String serverhosting;
	private Integer status;
	private Integer commendval;
	private Integer channel;
	private Long rolenum;
	private String code;
	private Integer sort;
	private String remark;
	private Set tgsmServerUserroleses = new HashSet(0);

	public TgsmServers() {
	}

	public TgsmServers(String servername, String serverhosting, Integer status, Integer commendval,
			Long rolenum, String code, Integer sort, String remark, Set tgsmServerUserroleses) {
		this.servername = servername;
		this.serverhosting = serverhosting;
		this.status = status;
		this.commendval = commendval;
		this.code = code;
		this.sort = sort;
		this.remark = remark;
		this.tgsmServerUserroleses = tgsmServerUserroleses;
	}

	public Long getServerid() {
		return this.serverid;
	}

	public void setServerid(Long serverid) {
		this.serverid = serverid;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getCommendval() {
		return commendval;
	}

	public void setCommendval(Integer commendval) {
		this.commendval = commendval;
	}

	public Integer getChannel() {
		return channel;
	}

	public void setChannel(Integer channel) {
		this.channel = channel;
	}

	public Long getRolenum() {
		return rolenum;
	}

	public void setRolenum(Long rolenum) {
		this.rolenum = rolenum;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getServername() {
		return this.servername;
	}

	public void setServername(String servername) {
		this.servername = servername;
	}

	public String getServerhosting() {
		return this.serverhosting;
	}

	public void setServerhosting(String serverhosting) {
		this.serverhosting = serverhosting;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getTgsmServerUserroleses() {
		return this.tgsmServerUserroleses;
	}

	public void setTgsmServerUserroleses(Set tgsmServerUserroleses) {
		this.tgsmServerUserroleses = tgsmServerUserroleses;
	}

}
