package cn.game.rjserver.uc.entity;

// Generated 2015-2-2 14:16:28 by Hibernate Tools 3.4.0.CR1

/**
 * TgsmSdktype generated by hbm2java
 */
public class TgsmSdktype implements java.io.Serializable {

	private long id;
	private Integer sdktype;
	private String appkey;
	private String sdkname;

	public TgsmSdktype() {
	}

	public TgsmSdktype(long id) {
		this.id = id;
	}

	public TgsmSdktype(long id, Integer sdktype, String appkey, String sdkname) {
		this.id = id;
		this.sdktype = sdktype;
		this.appkey = appkey;
		this.sdkname = sdkname;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getSdktype() {
		return this.sdktype;
	}

	public void setSdktype(Integer sdktype) {
		this.sdktype = sdktype;
	}

	public String getAppkey() {
		return this.appkey;
	}

	public void setAppkey(String appkey) {
		this.appkey = appkey;
	}

	public String getSdkname() {
		return this.sdkname;
	}

	public void setSdkname(String sdkname) {
		this.sdkname = sdkname;
	}

}
