package cn.game.rjserver.uc.entity;

// Generated 2014-3-7 13:54:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TgsmServerUserroles generated by hbm2java
 */
public class TgsmServerUserroles implements java.io.Serializable {

	private Long surolesid;
	private TgsmServers tgsmServers;
	private Long uid;
	private Long uroleid;
	private int rolelevel;
	private String rolenikename;
	private String rolehead;
	private Date createdate;

	public TgsmServerUserroles() {
	}

	public TgsmServerUserroles(TgsmServers tgsmServers, Long uid, Long uroleid, Date createdate) {
		this.tgsmServers = tgsmServers;
		this.uid = uid;
		this.uroleid = uroleid;
		this.createdate = createdate;
	}

	public Long getSurolesid() {
		return this.surolesid;
	}

	public void setSurolesid(Long surolesid) {
		this.surolesid = surolesid;
	}

	public TgsmServers getTgsmServers() {
		return this.tgsmServers;
	}

	public void setTgsmServers(TgsmServers tgsmServers) {
		this.tgsmServers = tgsmServers;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public Long getUroleid() {
		return this.uroleid;
	}

	public void setUroleid(Long uroleid) {
		this.uroleid = uroleid;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public int getRolelevel() {
		return rolelevel;
	}

	public void setRolelevel(int rolelevel) {
		this.rolelevel = rolelevel;
	}

	public String getRolenikename() {
		return rolenikename;
	}

	public void setRolenikename(String rolenikename) {
		this.rolenikename = rolenikename;
	}

	public String getRolehead() {
		return rolehead;
	}

	public void setRolehead(String rolehead) {
		this.rolehead = rolehead;
	}

}
