package cn.game.rjserver.uc.entity;

// Generated 2014-3-7 13:54:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TgsmGameupdate generated by hbm2java
 */
public class TgsmGameupdate implements java.io.Serializable {

	private Long resid;
	private long version;
	private String versionname;
	private String gamename;
	private String gamecode;
	private String versionserialcode;
	private String src;
	private String mustupdate;
	private Date createdate;

	public TgsmGameupdate() {
	}

	public TgsmGameupdate(String gamecode) {
		this.gamecode = gamecode;
	}

	public TgsmGameupdate(String versionname, String gamename, String gamecode, String versionserialcode, String src,
			String mustupdate, Date createdate) {
		this.versionname = versionname;
		this.gamename = gamename;
		this.gamecode = gamecode;
		this.versionserialcode = versionserialcode;
		this.src = src;
		this.mustupdate = mustupdate;
		this.createdate = createdate;
	}

	public Long getResid() {
		return this.resid;
	}

	public void setResid(Long resid) {
		this.resid = resid;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public String getVersionname() {
		return this.versionname;
	}

	public void setVersionname(String versionname) {
		this.versionname = versionname;
	}

	public String getGamename() {
		return this.gamename;
	}

	public void setGamename(String gamename) {
		this.gamename = gamename;
	}

	public String getGamecode() {
		return this.gamecode;
	}

	public void setGamecode(String gamecode) {
		this.gamecode = gamecode;
	}

	public String getVersionserialcode() {
		return this.versionserialcode;
	}

	public void setVersionserialcode(String versionserialcode) {
		this.versionserialcode = versionserialcode;
	}

	public String getSrc() {
		return this.src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public String getMustupdate() {
		return this.mustupdate;
	}

	public void setMustupdate(String mustupdate) {
		this.mustupdate = mustupdate;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
