package cn.game.rjserver.uc.entity;

// Generated 2014-3-7 13:54:59 by Hibernate Tools 3.4.0.CR1

/**
 * TucOthersdkUser generated by hbm2java
 */
public class TucOthersdkUser implements java.io.Serializable {

	private Long totherid;
	private TucUsers tucUsers;
	private String sdkuid;
	private String sdkuname;
	private String sdktype;
	private String sdksid;
	private String status;

	public TucOthersdkUser() {
	}

	public TucOthersdkUser(TucUsers tucUsers) {
		this.tucUsers = tucUsers;
	}

	public TucOthersdkUser(TucUsers tucUsers, String sdkuid, String sdkuname, String sdktype, String sdksid,
			String status) {
		this.tucUsers = tucUsers;
		this.sdkuid = sdkuid;
		this.sdkuname = sdkuname;
		this.sdktype = sdktype;
		this.sdksid = sdksid;
		this.status = status;
	}

	public Long getTotherid() {
		return this.totherid;
	}

	public void setTotherid(Long totherid) {
		this.totherid = totherid;
	}

	public TucUsers getTucUsers() {
		return this.tucUsers;
	}

	public void setTucUsers(TucUsers tucUsers) {
		this.tucUsers = tucUsers;
	}

	public String getSdkuid() {
		return this.sdkuid;
	}

	public void setSdkuid(String sdkuid) {
		this.sdkuid = sdkuid;
	}

	public String getSdkuname() {
		return this.sdkuname;
	}

	public void setSdkuname(String sdkuname) {
		this.sdkuname = sdkuname;
	}

	public String getSdktype() {
		return this.sdktype;
	}

	public void setSdktype(String sdktype) {
		this.sdktype = sdktype;
	}

	public String getSdksid() {
		return this.sdksid;
	}

	public void setSdksid(String sdksid) {
		this.sdksid = sdksid;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
