package cn.game.rjserver.uc.entity;

// Generated 2014-3-7 13:54:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TucUsers generated by hbm2java
 */
public class TucUsers implements java.io.Serializable {

	private Long uid;
	private String useraccount;
	private String userpwd;
	private String uname;
	private Date createdate;
	private String deleteflag;
	private String remark;
	private Set tucUserLoginlogs = new HashSet(0);
	private Set tucUserinfos = new HashSet(0);
	private Set tucUserLogoutlogs = new HashSet(0);
	private Set tucOthersdkUsers = new HashSet(0);

	public TucUsers() {
	}

	public TucUsers(Date createdate) {
		this.createdate = createdate;
	}

	public TucUsers(String useraccount, String userpwd, String uname, Date createdate, 
			String deleteflag, String remark, Set tucUserLoginlogs,
			Set tucUserinfos, Set tucUserLogoutlogs, Set tucOthersdkUsers) {
		this.useraccount = useraccount;
		this.userpwd = userpwd;
		this.uname = uname;
		this.createdate = createdate;
		this.deleteflag = deleteflag;
		this.remark = remark;
		this.tucUserLoginlogs = tucUserLoginlogs;
		this.tucUserinfos = tucUserinfos;
		this.tucUserLogoutlogs = tucUserLogoutlogs;
		this.tucOthersdkUsers = tucOthersdkUsers;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public String getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(String useraccount) {
		this.useraccount = useraccount;
	}

	public String getUserpwd() {
		return this.userpwd;
	}

	public void setUserpwd(String userpwd) {
		this.userpwd = userpwd;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}


	public String getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getTucUserLoginlogs() {
		return this.tucUserLoginlogs;
	}

	public void setTucUserLoginlogs(Set tucUserLoginlogs) {
		this.tucUserLoginlogs = tucUserLoginlogs;
	}

	public Set getTucUserinfos() {
		return this.tucUserinfos;
	}

	public void setTucUserinfos(Set tucUserinfos) {
		this.tucUserinfos = tucUserinfos;
	}

	public Set getTucUserLogoutlogs() {
		return this.tucUserLogoutlogs;
	}

	public void setTucUserLogoutlogs(Set tucUserLogoutlogs) {
		this.tucUserLogoutlogs = tucUserLogoutlogs;
	}

	public Set getTucOthersdkUsers() {
		return this.tucOthersdkUsers;
	}

	public void setTucOthersdkUsers(Set tucOthersdkUsers) {
		this.tucOthersdkUsers = tucOthersdkUsers;
	}

}
