package cn.game.rjserver.uc.entity;

// Generated 2014-3-7 13:54:59 by Hibernate Tools 3.4.0.CR1

/**
 * TucUserinfo generated by hbm2java
 */
public class TucUserinfo implements java.io.Serializable {

	private Long userinfoid;
	private TucUsers tucUsers;
	private String email;
	private String mobile;
	private Long usercoin;
	private String remark;
	private String imei;
	private String imsi;
	private Long screenwidth;
	private Long screenheight;
	private Long gameversion;
	private String systemsdk;
	private String systemversion;
	private String channel;
	private String phonemode;
	private String userip;
	private String identifycard;
	private String smsverifycode;

	public TucUserinfo() {
	}

	public TucUserinfo(TucUsers tucUsers, String email, String mobile, Long usercoin,
			String remark, String imei, String imsi, Long screenwidth, Long screenheight,
			Long gameversion, String systemsdk, String systemversion, String channel,
			String phonemode, String userip, String smsverifycode, String identifycard) {
		this.tucUsers = tucUsers;
		this.mobile = mobile;
		this.email = email;
		this.usercoin = usercoin;
		this.remark = remark;
		this.smsverifycode = smsverifycode;
		this.imei = imei;
		this.imsi = imsi;
		this.screenwidth = screenwidth;
		this.screenheight = screenheight;
		this.gameversion = gameversion;
		this.systemsdk = systemsdk;
		this.systemversion = systemversion;
		this.channel = channel;
		this.phonemode = phonemode;
		this.userip = userip;
	}

	public Long getUserinfoid() {
		return this.userinfoid;
	}

	public void setUserinfoid(Long userinfoid) {
		this.userinfoid = userinfoid;
	}

	public TucUsers getTucUsers() {
		return this.tucUsers;
	}

	public void setTucUsers(TucUsers tucUsers) {
		this.tucUsers = tucUsers;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getUsercoin() {
		return this.usercoin;
	}

	public void setUsercoin(Long usercoin) {
		this.usercoin = usercoin;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getSmsverifycode() {
		return this.smsverifycode;
	}

	public void setSmsverifycode(String smsverifycode) {
		this.smsverifycode = smsverifycode;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getImsi() {
		return this.imsi;
	}

	public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	public Long getScreenwidth() {
		return this.screenwidth;
	}

	public void setScreenwidth(Long screenwidth) {
		this.screenwidth = screenwidth;
	}

	public Long getScreenheight() {
		return this.screenheight;
	}

	public void setScreenheight(Long screenheight) {
		this.screenheight = screenheight;
	}

	public Long getGameversion() {
		return this.gameversion;
	}

	public void setGameversion(Long gameversion) {
		this.gameversion = gameversion;
	}

	public String getSystemsdk() {
		return this.systemsdk;
	}

	public void setSystemsdk(String systemsdk) {
		this.systemsdk = systemsdk;
	}

	public String getSystemversion() {
		return this.systemversion;
	}

	public void setSystemversion(String systemversion) {
		this.systemversion = systemversion;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getPhonemode() {
		return this.phonemode;
	}

	public void setPhonemode(String phonemode) {
		this.phonemode = phonemode;
	}

	public String getUserip() {
		return this.userip;
	}

	public void setUserip(String userip) {
		this.userip = userip;
	}

	public String getIdentifycard() {
		return this.identifycard;
	}

	public void setIdentifycard(String identifycard) {
		this.identifycard = identifycard;
	}

}
